### ISSUE TITLE
sage --branch sage-8 doesn't exist anymore

### ISSUE THREAD

**Issue by kross-aeg** [roots/roots-example-project.com#59]
## Bug reports and feature requests

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a bug report for the roots-example-project.com repo and **not** for Trellis, Bedrock, Sage or Soil
- [x] I've read the docs for [Trellis](https://roots.io/trellis/docs), [Bedrock](https://roots.io/bedrock/docs), [Sage](https://roots.io/sage/docs) and [Soil](https://github.com/roots/soil/blob/master/README.md) (if applicable) and followed them
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) forums

## Bug report

`git clone --depth=1 --branch sage-8 git@github.com:roots/sage.git site/web/app/themes/sage && rm -rf site/web/app/themes/sage/.git` fails.

**Comment by kross-aeg** [comment]
I tried removing the branch flag and cloning the sage master and then bower up results in "no bower.json file found."

**Comment by mmirus** [comment]
Hey @kirkbross - we just now updated the Sage-related bits of this example project, so take a look and see if that helps. You may still run into other problems until more work is done to bring this fully up to date, however. If you do, you might have better luck using the docs on https://roots.io/ instead of trying with the example project. Thanks for reporting this issue!
